#ifndef __IVCLOCK_BSP_H__
#define __IVCLOCK_BSP_H__

#define POWER_33_EN_Pin GPIO_PIN_13
#define POWER_33_EN_GPIO_Port GPIOC
#define POWER_50_EN_Pin GPIO_PIN_1
#define POWER_50_EN_GPIO_Port GPIOA
#define POWER_490_EN_Pin GPIO_PIN_11
#define POWER_490_EN_GPIO_Port GPIOA
#define BATTERY_MON_Pin GPIO_PIN_4
#define BATTERY_MON_GPIO_Port GPIOA

#define I2C_SCL_Pin GPIO_PIN_6
#define I2C_SCA_Pin GPIO_PIN_7
#define I2C_SCL_GPIO_Port GPIOB
#define I2C_SCA_GPIO_Port GPIOB
#define TIM1_ETR_Pin GPIO_PIN_12
#define TIM1_ETR_GPIO_Port GPIOA
#define TIM3_CH1_Pin GPIO_PIN_6
#define TIM3_CH1_GPIO_Port GPIOA
#define IV18_BLANK_Pin GPIO_PIN_13
#define IV18_BLANK_GPIO_Port GPIOB
#define IV18_LOAD_Pin GPIO_PIN_14
#define IV18_LOAD_GPIO_Port GPIOB
#define IV18_CLK_Pin GPIO_PIN_15
#define IV18_CLK_GPIO_Port GPIOB
#define IV18_DIN_Pin GPIO_PIN_8
#define IV18_DIN_GPIO_Port GPIOA
#define INT_KEY_MOD_Pin GPIO_PIN_3
#define INT_KEY_MOD_GPIO_Port GPIOB
#define INT_KEY_MOD_EXTI_IRQn EXTI3_IRQn
#define INT_KEY_SET_Pin GPIO_PIN_4
#define INT_KEY_SET_GPIO_Port GPIOB
#define INT_KEY_SET_EXTI_IRQn EXTI4_IRQn
#define INT_BT_Pin GPIO_PIN_5
#define INT_BT_GPIO_Port GPIOB
#define INT_BT_EXTI_IRQn EXTI9_5_IRQn
#define INT_ALARM_Pin GPIO_PIN_8
#define INT_ALARM_GPIO_Port GPIOB
#define INT_ALARM_EXTI_IRQn EXTI9_5_IRQn
#define INT_ACC_Pin GPIO_PIN_9
#define INT_ACC_GPIO_Port GPIOB
#define INT_ACC_EXTI_IRQn EXTI9_5_IRQn

#define BSP_ERROR_INTERNAL -1
#define BSP_ERROR_NONE 0

#endif